name: .NET Core CI with Docker

on:
  push:
    branches:
      - develop  # main 브랜치에 푸시될 때만 실행
  pull_request:
    branches:
      - develop  # main 브랜치로의 Pull Request가 생성될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu 환경에서 실행

    steps:
      # 1단계: 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2단계: Docker Buildx 설정 (Docker가 이미 설치되어 있음)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3단계: Docker 이미지 빌드
      - name: Build the Docker image
        run: |
          docker build -t my-dotnet-app .

      # 4단계: Docker 컨테이너 실행
      - name: Run Docker container
        run: |
          docker run -d -p 8080:80 my-dotnet-app

      # 5단계: 컨테이너 내부에서 테스트 실행
      - name: Run tests in the Docker container
        run: |
          docker exec my-dotnet-app dotnet test

      # 6단계: Docker 이미지 푸시 (옵션)
      - name: Push Docker image to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          docker login -u ${{ secrets.aaa9758 }} -p ${{ secrets.roqkfwk1! }}
          docker tag my-dotnet-app:latest yourdockerhubusername/my-dotnet-app:latest
          docker push yourdockerhubusername/my-dotnet-app:latest
