name: .NET Core CI with Docker

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu 환경에서 실행

    steps:
      # 1단계: 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2단계: Docker Buildx 설정 (Docker가 이미 설치되어 있음)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3단계: Docker 이미지 빌드
      - name: Build the Docker image
        run: |
          docker build -t my-dotnet-app .

      # 4단계: Docker 컨테이너 실행
      - name: Run Docker container
        run: |
          docker run -d -p 8080:80 --name my-dotnet-container my-dotnet-app
          docker ps  # 실행 중인 컨테이너 목록 확인
          docker logs my-dotnet-container  # 컨테이너 로그 출력

      # 5단계: 컨테이너 내부에서 테스트 실행
      - name: Run tests in the Docker container
        run: |
          docker exec my-dotnet-container dotnet test

      # 6단계: Docker 이미지 푸시 (develop 브랜치에서만 푸시)
      - name: Push Docker image to Docker Hub
        if: github.ref == 'refs/heads/develop'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag my-dotnet-app:latest yourdockerhubusername/my-dotnet-app:latest
          docker push yourdockerhubusername/my-dotnet-app:latest
